app = "http-log-server"
primary_region = "lax"

#[env]
#  TOKEN = ""

[http_service]
  internal_port = 8888
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "http_log_data"
  destination = "/data"